## Summary {#sec-gzlms-summary .unnumbered}

### Canonical link functions

| Distribution | Useful for... | Canonical link function | Interpretation |
|------------------|--------------------|------------------|---------------------|
| Gamma | Right skewed distributions | log | Percent change in outcome associated with unit change in predictor. |
| Poisson | Count outcomes with low dispersion | log | Percent change in outcome associated with unit change in predictor. |
| Negative-Binomial | Count outcomes with high dispersion | log | Percent change in outcome associated with unit change in predictor. |
| Zero-inflated | Any outcome with excess of zeros generated by a secondary process | Logit for zero-inflation component | Change in odds of outcome associated with unit change of the predictor |
| Logistic models | Categorical outcomes with two levels | logit | Change in odds of outcome associated with unit change of the predictor |
| Ordinal outcomes | Categorical outcomes with ordered levels (incl. Likert scales) | logit | Change in odds of belonging to higher levels associated with unit change of the predictor |
