```{r eval=FALSE, message=FALSE}
library(easystats) 
library(tidyverse) 

belay_tib <- here::here("data/climbing_data.csv") |> 
  readr::read_csv() 
```


```{r eval=FALSE, eval=FALSE}
belay_tib
```


```{r eval=FALSE,}
#| tbl-cap: ""

belay_tib |> 
  describe_distribution(select = -subj_id) |> 
  display() 
```


```{r eval=FALSE, fig.align='center'}

belay_tib |> 
  ggplot2::ggplot(data = _, aes(x = factor(assisted_break), y = reaction_time)) + # <1>
  geom_point(alpha = 0.7, colour = "yellowgreen", position = position_jitter(width = 0.1)) + 
  stat_summary(fun.data = "mean_cl_normal") + 
  coord_cartesian(ylim = c(0, 1030.5)) + 
  labs(x = "Did the belayer used an assisted breaking device", y = "Reaction time (ms) to break the fall") + 
  theme_light() 
```


```{r eval=FALSE, fig.align='center', message=FALSE}

belay_tib |> 
  ggplot2::ggplot(data = _, aes(x = climbing_exp, y = reaction_time)) + 
  geom_point(alpha = 0.7, colour = "yellowgreen") + 
  stat_smooth(method = "lm", colour = "steelblue", fill = "steelblue") + 
  coord_cartesian(xlim = c(0, 10), ylim = c(0, 1030.5)) + 
  labs(x = "Belayer's climbing experience (in years)", y = "Reaction time (ms) to break the fall") + 
  theme_light() 
```


```{r eval=FALSE, fig.align="center"}

belay_tib |> 
  ggplot2::ggplot(data = _, aes(x = reaction_time)) + 
  geom_density(colour = "steelblue", fill = "steelblue", alpha = 0.1) + 
  labs(x = "Reaction time (ms) to break the fall", y = "Density") + 
  theme_light()
```


```{r eval=FALSE,}
belay_lm <- lm(reaction_time ~ assisted_break + climbing_exp + distracted + fall_m, data = belay_tib)
```


```{r eval=FALSE, fig.height=7, fig.width=8}

belay_lm |> check_model()
```


```{r eval=FALSE,}
belay_lm |> 
  performance() |> 
  display()
```


```{r eval=FALSE, message=FALSE}
belay_lm |> 
  test_wald() |> 
  display()
```


```{r eval=FALSE, message=FALSE}
belay_rob <- robustbase::lmrob(reaction_time ~ assisted_break + climbing_exp + distracted + fall_m, data = belay_tib)
```


```{r eval=FALSE,}
#| tbl-cap: ""

belay_rob |> 
  parameters() |> 
  display()
```


```{r eval=FALSE,}
belay_tib[1, ] |> 
  display()
```


```{r eval=FALSE,}
assisted_break_i <- 0 
climbing_exp_i <- 3.1
distracted_i <- 1
fall_m_i <- 2.1 

689.29 - 26.77 * assisted_break_i - 53.49 * climbing_exp_i + 50.84 * distracted_i + 76.16 * fall_m_i
```


```{r eval=FALSE,}
residual_i <- belay_rob$residuals[1] # extract the residual for the first participant

689.29 - 26.77 * assisted_break_i - 53.49 * climbing_exp_i + 50.84 * distracted_i + 76.16 * fall_m_i + residual_i
```


```{r eval=FALSE, eval=FALSE}
belay_rob$fitted.values
```


```{r eval=FALSE,}
belay_rob$fitted.values[1]
```


```{r eval=FALSE,}
prediction_tib <- tibble::tibble(
  climbing_exp = 0:20,
  assisted_break = 0,
  distracted = 0,
  fall_m = 1.82
)

```


```{r eval=FALSE, eval=FALSE}
prediction_tib
```


```{r eval=FALSE, eval=FALSE}
predict(belay_rob, prediction_tib)
```


```{r eval=FALSE,}
prediction_tib <- prediction_tib |>  
  dplyr::mutate( 
    predicted_rt = predict(belay_rob, prediction_tib) 
  )
```


```{r eval=FALSE, eval=FALSE}
prediction_tib
```


```{r eval=FALSE, fig.align='center', message=FALSE}

belay_tib |> 
  ggplot2::ggplot(data = _, aes(x = climbing_exp, y = reaction_time)) + 
  geom_point(alpha = 0.7, colour = "yellowgreen") + 
  stat_smooth(colour = "darkred", data = prediction_tib, aes(x = climbing_exp, y = predicted_rt)) +
  labs(x = "Belayer's climbing experience (in years)", y = "Reaction time (ms) to break the fall") + 
  theme_light() 
```


```{r eval=FALSE,}
belay_glm <- glm( 
  reaction_time ~ assisted_break + climbing_exp + distracted + fall_m, 
  family = gaussian(link = "identity"), 
  data = belay_tib 
)
```


```{r eval=FALSE, eval=FALSE}
belay_glm |> 
  check_model()  

belay_glm |> 
  performance()  

belay_glm |> 
  test_wald() 

```


```{r eval=FALSE,}
belay_lm |> 
  parameters() |> 
  display()
```


```{r eval=FALSE,}
belay_glm |> 
  parameters() |> 
  display()
```


