<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Generalised Linear Models – Advanced Statistics 25/26</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./01a_gzlms_skewed.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="site_libs/datatables-binding-0.33/datatables.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="assets/webex.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_gzlms.html">Generalised Linear Models</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Advanced Statistics 25/26</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome to Advanced Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01_gzlms.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Generalised Linear Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01a_gzlms_skewed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Modelling skewness</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01b_gzlms_counts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Modelling counts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01c_gzlms_ordinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Modelling ordinal outcomes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01d_gzlms_summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summary</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02_ma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Meta-analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02a_ma_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introduction to meta-analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b_ma_advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Advanced meta-analytic methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02c_ma_assessment_support.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Assessment support</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03_measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Measurement</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03a_measurement_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">EFA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03b_measurement_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">CFA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03c_measurement_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Measurement invariance</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_cex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Computer Exam</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_open_topic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Open Topic</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="4">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#scenario-gzlms" id="toc-scenario-gzlms" class="nav-link active" data-scroll-target="#scenario-gzlms">Scenario</a>
  <ul>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The data</a></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">Descriptive statistics</a></li>
  <li><a href="#visualisation" id="toc-visualisation" class="nav-link" data-scroll-target="#visualisation">Visualisation</a></li>
  </ul></li>
  <li><a href="#ordinary-least-squares-estimation" id="toc-ordinary-least-squares-estimation" class="nav-link" data-scroll-target="#ordinary-least-squares-estimation">Ordinary Least Squares estimation</a>
  <ul>
  <li><a href="#fit-the-model" id="toc-fit-the-model" class="nav-link" data-scroll-target="#fit-the-model">Fit the model</a></li>
  <li><a href="#check-model-assumptions" id="toc-check-model-assumptions" class="nav-link" data-scroll-target="#check-model-assumptions">Check model assumptions</a></li>
  <li><a href="#check-model-fit" id="toc-check-model-fit" class="nav-link" data-scroll-target="#check-model-fit">Check model fit</a></li>
  </ul></li>
  <li><a href="#gzlms-robust-main" id="toc-gzlms-robust-main" class="nav-link" data-scroll-target="#gzlms-robust-main">Robust estimation</a></li>
  <li><a href="#making-predictions" id="toc-making-predictions" class="nav-link" data-scroll-target="#making-predictions">Making predictions</a>
  <ul>
  <li><a href="#predictions-within-the-observed-data" id="toc-predictions-within-the-observed-data" class="nav-link" data-scroll-target="#predictions-within-the-observed-data">Predictions within the observed data</a></li>
  <li><a href="#sec-going-beyond-the-data" id="toc-sec-going-beyond-the-data" class="nav-link" data-scroll-target="#sec-going-beyond-the-data">Going beyond the data</a></li>
  </ul></li>
  <li><a href="#introduction-to-gzlm" id="toc-introduction-to-gzlm" class="nav-link" data-scroll-target="#introduction-to-gzlm">Introduction to GzLM</a>
  <ul>
  <li><a href="#how-is-gzlm-different-to-glm" id="toc-how-is-gzlm-different-to-glm" class="nav-link" data-scroll-target="#how-is-gzlm-different-to-glm">How is GzLM different to GLM?</a>
  <ul class="collapse">
  <li><a href="#maximum-likelihood-estimation" id="toc-maximum-likelihood-estimation" class="nav-link" data-scroll-target="#maximum-likelihood-estimation">Maximum Likelihood estimation</a></li>
  <li><a href="#sec-conditional-distributions" id="toc-sec-conditional-distributions" class="nav-link" data-scroll-target="#sec-conditional-distributions">Conditional distributions</a></li>
  <li><a href="#sec-mean-variance-relationship" id="toc-sec-mean-variance-relationship" class="nav-link" data-scroll-target="#sec-mean-variance-relationship">Mean-variance relationship</a></li>
  </ul></li>
  <li><a href="#sec-fitting-gzlm-in-r" id="toc-sec-fitting-gzlm-in-r" class="nav-link" data-scroll-target="#sec-fitting-gzlm-in-r">Fitting GzLM in R</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul>
  <li><a href="#welcome-to-the-family" id="toc-welcome-to-the-family" class="nav-link" data-scroll-target="#welcome-to-the-family">Welcome to the family</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul>
  <li><a href="#what-does-this-code-do" id="toc-what-does-this-code-do" class="nav-link" data-scroll-target="#what-does-this-code-do">What does this code do?</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Generalised Linear Models</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>“Generalised Linear Model” is an umbrella term describing a flexible statistical modelling framework. Unlike the “<em>General</em> Linear Model”, which is often inadequate in real-life situations, Generalised Linear Models allow us to model a range of realistic scenarios without assuming an unrealistic data structure.</p>
<p>We’ll use the abbreviation GzLM for “Generalised Linear Model” and GLM for “General Linear Model”, however note that it’s common for people out in the wild to refer to either with GLM. Statisticians and data scientists are cool like that.</p>
<p>Before jumping into the GzLM, let’s run through a quick recap of the GLM, how it works and its limitations. Most of this should be familiar from <em>An Adventure in Statistics</em> - if you’re feeling confident about the ins and outs of the Ordinary Least Squares (OLS) estimation and robust estimation, you can read the <strong>Scenario</strong> below, skim through the code, and then move straight to the section <a href="#making-predictions">Making predictions</a>.</p>
<section id="scenario-gzlms" class="level2">
<h2 class="anchored" data-anchor-id="scenario-gzlms">Scenario</h2>
<blockquote class="blockquote">
<p>A researcher in sports psychology is interested in understanding the factors related to the reaction times of belayers<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> when breaking a fall of their climbing partners. She set up ultra-high resolution cameras at the local gym, then reviews the footage and records: the time it took for the belayer to effectively stop the fall after the climber lost control in milliseconds (<code>reaction_time</code>); whether the belayer used an assisted-breaking device (<code>assisted_break</code> - no/yes); and whether the belayer was talking to others or was otherwise distracted (<code>distracted</code> - no/yes). The researcher also collected information about the participants’ climbing experience in years (<code>climbing_exp</code>), and the length of the climbers’ fall in metres (<code>fall_m</code>).</p>
<p>The researcher hypothesises the following:</p>
<p>H<sub>1</sub>: More experienced belayers will be faster to catch falls.</p>
<p>H<sub>2</sub>: Belayers using an assisted breaking device will be faster to catch falls.</p>
</blockquote>
<section id="the-data" class="level3">
<h3 class="anchored" data-anchor-id="the-data">The data</h3>
<p>The (fictional) dataset is stored in the file <a href="data/climbing_data.csv"><code>climbing_data.csv</code></a> . First, let’s load up the necessary packages. Then, assuming you have <a href="index.html#importing-datasets">imported the dataset</a> into the <code>data</code> folder on Posit Cloud, you can read it into your R session as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-1"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-1-1" class="code-annotation-target"><a href="#annotated-cell-1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(easystats)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-1-2" class="code-annotation-target"><a href="#annotated-cell-1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="annotated-cell-1-3"><a href="#annotated-cell-1-3" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-1-4" class="code-annotation-target"><a href="#annotated-cell-1-4" aria-hidden="true" tabindex="-1"></a>belay_tib <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/climbing_data.csv"</span>) <span class="sc">|&gt;</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-1-5" class="code-annotation-target"><a href="#annotated-cell-1-5" aria-hidden="true" tabindex="-1"></a>  readr<span class="sc">::</span><span class="fu">read_csv</span>()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-1" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="1" data-code-annotation="1">Load the <code>easystats</code> package</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="2" data-code-annotation="2">Load the <code>tidyverse</code> package</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="4" data-code-annotation="3">Specify the directory of the dataset with the <code>here</code> function.</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="5" data-code-annotation="4">Read the data, storing the result of this code into an object called <code>belay_tib</code>.</span>
</dd>
</dl>
</div>
</div>
<p>Let’s inspect the dataset to make sure it read in properly:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>belay_tib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div id="tbl-gzlms-tib" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-gzlms-tib-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-gzlms-tib-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-c86510d37e8428da6b9e" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-c86510d37e8428da6b9e">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152"],[1017,8004,4775,9725,8462,4050,8789,1301,8522,1799,9941,8229,1129,8921,878,8677,7845,5922,6526,5071,2900,7075,4650,9638,2159,3476,1948,2580,1530,7289,4633,6519,4344,1222,2858,5400,9888,526,1069,5522,8214,5838,5862,6337,5491,9320,7494,9175,1791,9831,4939,465,7976,9392,3863,9326,8276,1895,3101,3990,6877,6764,1328,8749,8479,6473,6995,9714,858,6763,9182,316,733,6273,4907,5051,2330,9359,6429,3992,1706,501,6655,536,6881,7507,7514,3747,5163,29,1942,4934,1820,2281,9509,1966,8561,4182,5603,5742,8547,5939,6956,9265,8553,9532,9458,6902,2866,8943,219,8327,532,3123,9104,6611,2178,5936,7233,5932,4455,2153,1148,1101,1242,1218,4115,8465,418,6563,867,4499,3821,9803,5897,818,4730,664,719,500,3045,6816,6373,8615,8159,8613,9181,3598,3700,5136,9346,8696],[847.4,492.59,375.49,352.27,374.9,507.26,720.76,450.12,498.25,408.13,680.63,597.1799999999999,464.92,466.91,465.93,511.52,393.08,510.2,1012.92,719.58,474.54,480.65,726.26,623.8099999999999,504.51,426.75,555.63,617.36,524.91,382.82,744.97,532.8200000000001,606.83,407.54,538.22,549.16,337.54,388.25,675.01,896.88,610.86,327.24,662.01,375.63,454.14,385.75,421.88,387.31,608.49,427.08,530.78,738.03,738.66,472.86,387.95,485.63,656.26,394.82,524.21,465.98,449.6,436.23,1030.44,350.88,969.97,718.49,567.13,504.95,687.0599999999999,536.2,354.74,430.92,464.35,334.5,649.84,513.72,368.37,466.05,395.78,580.58,557.79,450.23,434.5,679.4299999999999,417.41,324.69,572.77,476.85,356.68,523.86,514.66,467.78,562.4,514.9,621.3200000000001,316.12,574.77,326.07,753.0700000000001,923.14,461.9,660.66,865.96,491.81,488.86,413.11,428.13,377.32,631.6799999999999,646.78,463.07,616.15,388.05,361.37,523.05,520.04,597.17,530.75,389.5,513.25,524.92,397.92,394.91,456.36,421.02,774.39,578.01,569.16,436.61,577.49,361.05,597.86,580.88,437.5,532.65,518.86,410.36,535.67,365.62,533.9299999999999,619.79,505.76,584.34,730.73,373.1,455,561.55,553.95,433.43,374.33,441.15,431.4],[0,1,0,1,1,0,0,1,0,1,1,1,0,0,1,0,1,1,1,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,0,1,1,0,0,0,1,0,1,1,0,1,1,1,0,1,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,0,0,1,1,0,1,0,0,0,1,1,0,0,1,1,0,1,1,0,0,1,0,1,1,0,1,0,1,1,0,1,0,0,1,1,1,1,1,0,1,1,0,1,0,1,1,1,1,1,0,1,1,1,0,0,1,1,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,1,1,1,1,0,0,1,0,0],[1,0,0,0,0,0,1,1,0,0,0,1,1,1,1,1,0,1,1,1,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,1,0,1,1,1,0,0,0,1,0,0,1,1,0,0,0,1,1,1,0,1,1,1,0,1,0,1,1,0,0,0,1,1,1,1,0,1,1,1,1,1,0,1,1,0,1,1,1,0,0,1,0,0,0,1,0,1,0,0,0,1,0,1,1,1,0,0,1,1,1,1,0,1,1,1,1,0,1,0,0,1,0,1,0,1,0,1,0,0,1,1,0,1,1,0,0,1,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,1,0,0,0],[3.1,7.3,7.6,9.300000000000001,6.6,5.9,5.1,7.1,5.1,6.2,5.2,3.9,7.4,6.2,6.7,6.2,8.6,7.1,2.1,6.2,5.7,6.7,4.3,4.3,6.9,5.9,6.2,2.1,4.8,6.5,6.8,5.6,4.4,6.9,5.9,6.4,7.1,4.9,5.3,3,5.1,7.2,5.1,9.699999999999999,6.1,9.6,7.1,7.3,5.1,7,5.2,6,5.8,6.7,6.7,8,5.8,7.4,3.2,8.6,5.8,5.7,7,7.2,3.3,3.5,5.1,5.3,4.4,3.8,7.9,7.9,5.8,8.6,5.9,6.7,5.1,9.300000000000001,8.199999999999999,5.7,6.8,7.1,6.4,2.2,6.9,8,4.5,7.3,8,5.7,5.3,6.6,5.2,5.6,5.7,7.9,3.9,6.5,4,5.6,5.1,5.6,5.7,8.199999999999999,6.1,6.9,7.8,7.7,4.6,4.3,8.1,6.5,5.6,7.9,5,6.3,5.1,7.7,6.6,6.5,6.2,6.8,5.6,7.4,5.6,5.6,6.3,5.1,7.7,4.9,8.4,5.7,4.5,6.9,6.6,4.9,7.2,6.8,7.1,4.7,6.7,6.1,5.6,4.7,5.2,6.6,3.6,6.3,7.7,6.9,6.9,9.199999999999999],[2.1,1.2,1.5,1.7,1.6,1.8,1.7,1.5,1.7,1.1,2.5,1.6,1.6,2.2,2,1.7,1.8,1.4,1.2,1.5,1.3,1.9,1.1,1.5,2.1,2.3,2.2,1.7,1.8,2.1,2.8,1.7,1.4,1.6,1.6,1.9,1.8,1.1,2.7,1.6,2,1.4,2.5,1.8,0.9,2.1,1.9,2,1.7,2.5,1.7,2.1,2.1,2.3,1.3,1.9,2,1.1,2.1,2.6,1.4,1,1.5,1.8,2.1,1.8,2.1,1.2,1.9,1.4,1.8,1.9,2.4,1.5,1.8,2.4,1.8,2.2,1.7,2,1.8,1.7,2,1.5,1.6,1.8,1.7,1.8,2,1.1,2.1,2.3,2.3,1.8,1.8,1.5,2,1.9,1.4,2.2,1.9,1.9,3,1.9,2.1,1.7,2.1,1.1,2.2,2.3,1.3,2.5,0.9,1.4,1.5,1.3,2.1,2.2,2.1,1.7,2.1,1.4,1.5,2.3,1.8,1.5,1.9,2.4,1.6,1.9,2.2,1.8,1.6,2.6,1.9,1.3,1.6,1.5,1.5,1.3,1.7,2.2,2.9,1.4,2.1,2.2,1.8,2,2,2,1.4,2]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>subj_id<\/th>\n      <th>reaction_time<\/th>\n      <th>assisted_break<\/th>\n      <th>distracted<\/th>\n      <th>climbing_exp<\/th>\n      <th>fall_m<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5,6]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"subj_id","targets":1},{"name":"reaction_time","targets":2},{"name":"assisted_break","targets":3},{"name":"distracted","targets":4},{"name":"climbing_exp","targets":5},{"name":"fall_m","targets":6}],"order":[],"autoWidth":false,"orderClasses":false},"selection":{"mode":"multiple","selected":null,"target":"row","selectable":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</figure>
</div>
</div>
<p><br></p>
<p>We have six variables here: the ID of the participant <code>subj_id</code> , the outcome <code>reaction_time</code> and four predictors as specified in the <a href="#scenario-gzlms">Scenario</a> above. <code>assisted_break</code> and <code>distracted</code> are currently encoded as 0s and 1s, 0 standing for “No” and 1 standing for “Yes”.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Factors and binary categorical predictors
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Ideally, categorical predictors should be encoded as factors with meaningful labels. However if a categorical predictor with two categories is coded as 0 and 1, we don’t strictly need to convert them into factors. Zeros and ones are exactly what we use when dummy coding, so we can use these variables as they are to fit a model. R will cope just fine and the statistics will be valid. The output will just not be as helpfully labelled, so we need to remember that the beta for these predictors will tell is how larger or smaller the estimate of the category coded as 1 is compared to the category coded as 0.</p>
<p>Situations where we absolutely <em>have to</em> convert into factors or out right dummy codes include: when the nummeric categories are different to 0 and 1 (e.g.&nbsp;they’re 1 and 2, or 2 and 3 for whatever reason) or when there are more than two categories. Especially in the latter case, it makes no sense to treat a categorical predictor with three categories as if it was continuous.</p>
</div>
</div>
</div>
</section>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">Descriptive statistics</h3>
<p>The next few steps should be familiar. We start by generating some descriptive summaries:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-3"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><a class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-3-1" class="code-annotation-target"><a href="#annotated-cell-3-1" aria-hidden="true" tabindex="-1"></a>belay_tib <span class="sc">|&gt;</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-3-2" class="code-annotation-target"><a href="#annotated-cell-3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">describe_distribution</span>(<span class="at">select =</span> <span class="sc">-</span>subj_id) <span class="sc">|&gt;</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-3-3" class="code-annotation-target"><a href="#annotated-cell-3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-3" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-lines="1" data-code-annotation="1">Take the object <code>belay_tib</code> -</span>
</dd>
<dt data-target-cell="annotated-cell-3" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-lines="2" data-code-annotation="2">Pipe it into <code>describe_distribution()</code> which will provide general descriptive summaries. We’re including some optional arguments:</span>
</dd>
<dt data-target-cell="annotated-cell-3" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-lines="3" data-code-annotation="3">Apply formatting to create a nicer looking table (optional, but useful for e.g.&nbsp;writing reports)</span>
</dd>
</dl>
</div>
<div id="tbl-gzlms-describe" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-gzlms-describe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-gzlms-describe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">SD</th>
<th style="text-align: center;">IQR</th>
<th style="text-align: center;">Range</th>
<th style="text-align: center;">Skewness</th>
<th style="text-align: center;">Kurtosis</th>
<th style="text-align: center;">n</th>
<th style="text-align: center;">n_Missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">reaction_time</td>
<td style="text-align: center;">523.14</td>
<td style="text-align: center;">141.68</td>
<td style="text-align: center;">172.73</td>
<td style="text-align: center;">(316.12, 1030.44)</td>
<td style="text-align: center;">1.21</td>
<td style="text-align: center;">1.79</td>
<td style="text-align: center;">152</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">assisted_break</td>
<td style="text-align: center;">0.52</td>
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">(0.00, 1.00)</td>
<td style="text-align: center;">-0.08</td>
<td style="text-align: center;">-2.02</td>
<td style="text-align: center;">152</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">distracted</td>
<td style="text-align: center;">0.49</td>
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">(0.00, 1.00)</td>
<td style="text-align: center;">0.03</td>
<td style="text-align: center;">-2.03</td>
<td style="text-align: center;">152</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">climbing_exp</td>
<td style="text-align: center;">6.14</td>
<td style="text-align: center;">1.48</td>
<td style="text-align: center;">1.97</td>
<td style="text-align: center;">(2.10, 9.70)</td>
<td style="text-align: center;">-0.22</td>
<td style="text-align: center;">0.28</td>
<td style="text-align: center;">152</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fall_m</td>
<td style="text-align: center;">1.82</td>
<td style="text-align: center;">0.41</td>
<td style="text-align: center;">0.60</td>
<td style="text-align: center;">(0.90, 3.00)</td>
<td style="text-align: center;">0.19</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">152</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><br></p>
<p>We have no missing values, for any of the variables (good to know). Reaction time (RT) is in millisecond so the average reaction time for stopping a fall was a little over half a second (523.14 ms). The quickest belayer caught a fall in 316 ms and the slowest in 1030 ms. On average, belayers had a climbing experience of 6.14 years, ranging from 2.1 to 9.7 years. Average fall length was 1.82 metres. The smallest recorded fall was 0.9 metres, the longest was 3 metres.We’re not interested in central tendency, dispersion, or skewness and kurtosis for the <code>assisted_break</code> and <code>distracted</code> (it makes no sense to inspect these for categorical predictors).</p>
<p>Climbing experience and fall distance show low levels of skewness and kurtosis. However, our outcome variable is positively skewed (skewness = 1.21), and has excess kurtosis substantially above 0 (kurtosis = 1.79).</p>
<p>This is not that surprising. Reaction times are bound at 0 (you cannot have a negative reaction time) and unbound on the opposite tail, so it really doesn’t make sense to expect a normal distribution, which is unbound on both ends. Even if we don’t have this intuition, reaction time is <em>the</em> best documented and most stereotypical variable known to have a skewed distribution. Despite this, researchers often model it with estimators that rely on normal distribution (somewhere in the process), simply because it’s convenient. So for now, we’re going to assume ignorance to see whether we can pry something meaningful out of the model using a regular linear model.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Normal distribution of the outcome
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Remember that when we’re fitting an OLS-based linear model, the normal distribution of the outcome variable is <strong><em>not</em></strong> one of the assumptions. The actual assumption refers to the errors in the population model, which are best checked by inspecting the model residuals. However, the outcome variable will often (but not always) have a similar distribution to the residuals. It is therefore useful to inspect it in the initial stage, but we’ll still need to run the residual diagnostics after we’ve fitted the model.</p>
</div>
</div>
</div>
</section>
<section id="visualisation" class="level3">
<h3 class="anchored" data-anchor-id="visualisation">Visualisation</h3>
<p>For data visualisation, we’ll want:</p>
<ol type="1">
<li>A plot showing the hypothesised relationships between each predictor and the outcome.</li>
<li>A plot showing the distribution of the outcome, just so we have a better sense of what the variable looks like</li>
</ol>
<p>Let’s start with H<sub>1</sub>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="annotated-cell-4"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-4-1"><a href="#annotated-cell-4-1" aria-hidden="true" tabindex="-1"></a>belay_tib <span class="sc">|&gt;</span> </span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-4-2" class="code-annotation-target"><a href="#annotated-cell-4-2" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span> _, <span class="fu">aes</span>(<span class="at">x =</span> climbing_exp, <span class="at">y =</span> reaction_time)) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-4-3" class="code-annotation-target"><a href="#annotated-cell-4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">colour =</span> <span class="st">"yellowgreen"</span>) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-4-4" class="code-annotation-target"><a href="#annotated-cell-4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">colour =</span> <span class="st">"steelblue"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-4-5" class="code-annotation-target"><a href="#annotated-cell-4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1030.5</span>)) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-4-6" class="code-annotation-target"><a href="#annotated-cell-4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Belayer's climbing experience (in years)"</span>, <span class="at">y =</span> <span class="st">"Reaction time (ms) to break the fall"</span>) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="6" onclick="event.preventDefault();">6</a><span id="annotated-cell-4-7" class="code-annotation-target"><a href="#annotated-cell-4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-4" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-lines="2" data-code-annotation="1">Specify the dataset and the aesthetics</span>
</dd>
<dt data-target-cell="annotated-cell-4" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-lines="3" data-code-annotation="2">Add raw data points</span>
</dd>
<dt data-target-cell="annotated-cell-4" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-lines="4" data-code-annotation="3">Add the line of best fit</span>
</dd>
<dt data-target-cell="annotated-cell-4" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-lines="5" data-code-annotation="4">Scale the y axis and the x axis to reflect the realistic scale of our outcome variable (the maximum value 1030.5 is based on values from <a href="#tbl-gzlms-describe" class="quarto-xref">Table&nbsp;<span>2</span></a>)</span>
</dd>
<dt data-target-cell="annotated-cell-4" data-target-annotation="5">5</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-lines="6" data-code-annotation="5">Add meaningful labels</span>
</dd>
<dt data-target-cell="annotated-cell-4" data-target-annotation="6">6</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-lines="7" data-code-annotation="6">Add a theme (optional but generally a good idea)</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<div id="fig-gzlms-h1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gzlms-h1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01_gzlms_files/figure-html/fig-gzlms-h1-1.png" id="fig-gzlms-h1" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-gzlms-h1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Learning about ggplots
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>ggplot</code> is a fantastic tool but the code is objectively difficult to remember - it’s chonky, and each line has far too many options for customisation. When working with ggplot code, don’t just copy and paste the whole code chunk and call it a day - instead, write the first line, run it, see what it does. Then write the second line, add it to the plot, and see what changes. And so on. This goes for any code that’s longer than just a couple of lines. By writing it line by line, you’ll get a better understanding of what the code does, which bits are crucial and which ones are just “nice to have”. For example, I didn’t need to change the colour of the points in line 3, nor did I need to add the jitter, or the labels for the x and y axis. Without these, the plot would still be understandable. But adding these elements the plot more readable and accessible.</p>
</div>
</div>
</div>
<p><br></p>
<p>Now let’s do the same for H<sub>2</sub></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="annotated-cell-5"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-5-1"><a href="#annotated-cell-5-1" aria-hidden="true" tabindex="-1"></a>belay_tib <span class="sc">|&gt;</span> </span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-5-2" class="code-annotation-target"><a href="#annotated-cell-5-2" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span> _, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(assisted_break), <span class="at">y =</span> reaction_time)) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-5-3" class="code-annotation-target"><a href="#annotated-cell-5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">colour =</span> <span class="st">"yellowgreen"</span>, <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>)) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-5-4" class="code-annotation-target"><a href="#annotated-cell-5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_cl_normal"</span>) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-5-5" class="code-annotation-target"><a href="#annotated-cell-5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1030.5</span>)) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-5-6" class="code-annotation-target"><a href="#annotated-cell-5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Did the belayer used an assisted breaking device"</span>, <span class="at">y =</span> <span class="st">"Reaction time (ms) to break the fall"</span>) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="6" onclick="event.preventDefault();">6</a><span id="annotated-cell-5-7" class="code-annotation-target"><a href="#annotated-cell-5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-5" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="2" data-code-annotation="1">Specify the dataset and which variable to put on each of the axes. Note that we’re wrapping <code>assisted_break</code> in the <code>factor()</code> function, so the plot treats it as such. This is optional. Again, it would have been better to convert the variable to the factor at the very beginning, but we’re keeping it as numeric for now because it makes some of the later calculations easier.</span>
</dd>
<dt data-target-cell="annotated-cell-5" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="3" data-code-annotation="2">Add raw data points - this is good for inspecting potentially unusual cases</span>
</dd>
<dt data-target-cell="annotated-cell-5" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="4" data-code-annotation="3">Add the mean and confidence intervals - this time, the predictor is categorical so we use <code>stat_summary</code> instead of <code>stat_smooth</code></span>
</dd>
<dt data-target-cell="annotated-cell-5" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="5" data-code-annotation="4">Scale the y axis</span>
</dd>
<dt data-target-cell="annotated-cell-5" data-target-annotation="5">5</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="6" data-code-annotation="5">Add meaningful labels</span>
</dd>
<dt data-target-cell="annotated-cell-5" data-target-annotation="6">6</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="7" data-code-annotation="6">Add a theme</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<div id="fig-gzlms-h2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gzlms-h2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01_gzlms_files/figure-html/fig-gzlms-h2-1.png" id="fig-gzlms-h2" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-gzlms-h2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2
</figcaption>
</figure>
</div>
</div>
</div>
<p>Finally, let’s have a look at the distribution of the outcome:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>belay_tib <span class="sc">|&gt;</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span> _, <span class="fu">aes</span>(<span class="at">x =</span> reaction_time)) <span class="sc">+</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">colour =</span> <span class="st">"steelblue"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Reaction time (ms) to break the fall"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span> </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-gzlms-outcome" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gzlms-outcome-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01_gzlms_files/figure-html/fig-gzlms-outcome-1.png" id="fig-gzlms-outcome" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-gzlms-outcome-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3
</figcaption>
</figure>
</div>
</div>
</div>
<p>No code description for this one - see if you can work it out!</p>
<p><br></p>
<p>From <a href="#fig-gzlms-h1" class="quarto-xref">Figure&nbsp;<span>1</span></a>, we see that there is quite a steep negative relationship between climbing experience of the belayer and reaction time - the more experience the belayer is, the shorter they take to respond. At a glance, it also seems like the belayers who used an assisted-breaking device were slightly faster to react compared to those who didn’t (<a href="#fig-gzlms-h2" class="quarto-xref">Figure&nbsp;<span>2</span></a>).</p>
<p>Finally, <a href="#fig-gzlms-outcome" class="quarto-xref">Figure&nbsp;<span>3</span></a> confirms what <a href="#tbl-gzlms-describe" class="quarto-xref">Table&nbsp;<span>2</span></a> told us - that the outcome variable is right-skewed, with most values clustered towards the lower end an asymmetrical right tail. Without further ado, let’s confidently ignore this fact and hope for the best when fit an OLS linear model.</p>
</section>
</section>
<section id="ordinary-least-squares-estimation" class="level2">
<h2 class="anchored" data-anchor-id="ordinary-least-squares-estimation">Ordinary Least Squares estimation</h2>
<section id="fit-the-model" class="level3">
<h3 class="anchored" data-anchor-id="fit-the-model">Fit the model</h3>
<p>We can fit the linear model with all four predictors as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>belay_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(reaction_time <span class="sc">~</span> assisted_break <span class="sc">+</span> climbing_exp <span class="sc">+</span> distracted <span class="sc">+</span> fall_m, <span class="at">data =</span> belay_tib)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Before diving straight into the result, we’ll need to check the model assumptions and assess the model fit.</p>
</section>
<section id="check-model-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="check-model-assumptions">Check model assumptions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>belay_lm <span class="sc">|&gt;</span> <span class="fu">check_model</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-gzlms-assumptions" class="quarto-float quarto-figure quarto-figure-center anchored" width="768">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gzlms-assumptions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01_gzlms_files/figure-html/fig-gzlms-assumptions-1.png" id="fig-gzlms-assumptions" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-gzlms-assumptions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4
</figcaption>
</figure>
</div>
</div>
</div>
<p>Right of the bat, we have problems. The posterior predictive check (row 1 left) shows that the distribution of values predicted by the model doesn’t align with the distribution observed in the dataset. There appears to be slight non-linearity, and the spread of the residuals is greater as we move right along the x axis (row 1 right) - this indicates the errors are heteroscedastic. This is confirmed by the fact that the line is not completely flat in row 2 left plot. There don’t appear to be any influential observations, but case 19 has Cook’s distance that is close to the cut-off of 0.8 (row 2 right). No particular issues with collinearity (row 3 left). Finally, the Q-Q plot in row 3 right confirms what we suspect based on the outcome distribution - that the distribution of the residuals is skewed with potentially extreme values, as evident by the right tail lifting above the horizontal reference line.</p>
</section>
<section id="check-model-fit" class="level3">
<h3 class="anchored" data-anchor-id="check-model-fit">Check model fit</h3>
<p>We can get the overall fit statistics:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>belay_lm <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">performance</span>() <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">AIC</th>
<th style="text-align: center;">AICc</th>
<th style="text-align: center;">BIC</th>
<th style="text-align: center;">R2</th>
<th style="text-align: center;">R2 (adj.)</th>
<th style="text-align: center;">RMSE</th>
<th style="text-align: center;">Sigma</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1848.0</td>
<td style="text-align: center;">1848.6</td>
<td style="text-align: center;">1866.1</td>
<td style="text-align: center;">0.48</td>
<td style="text-align: center;">0.47</td>
<td style="text-align: center;">101.54</td>
<td style="text-align: center;">103.26</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<p>And test the overall fit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>belay_lm <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">test_wald</span>() <span class="sc">|&gt;</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: right;">Model</th>
<th style="text-align: left;">df</th>
<th style="text-align: right;">df_diff</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Null model</td>
<td style="text-align: right;">lm</td>
<td style="text-align: left;">151</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Full model</td>
<td style="text-align: right;">lm</td>
<td style="text-align: left;">147</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">34.33</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
</tbody>
</table>
<p>Models were detected as nested (in terms of fixed parameters) and are compared in sequential order.</p>
</div>
</div>
<p><br></p>
<p>The model appears to be a good fit and a statistically significant improvement over a model where the reaction time is predicted from intercept alone, <em>F</em>(4,147) = 34.33, <em>p</em> &lt; .001 , explaining 48.3% of total variance, <em>R<sup>2</sup></em> = 0.48 , <em>R<sup>2</sup><sub>adj</sub></em> = 0.47 . However, before we congratulate ourselves, let’s remember that the model assumptions were violated in almost every respect, so we might want to address this in some way.</p>
</section>
</section>
<section id="gzlms-robust-main" class="level2">
<h2 class="anchored" data-anchor-id="gzlms-robust-main">Robust estimation</h2>
<p>Robust estimation is one approach that can be used for dealing with violated assumptions - instead of interpreting the parameters from the OLS model, we fit a robust model that is not sensitive (or less sensitive) to violated assumptions. We then use the parameter estimates from this model to draw conclusions about the hypotheses.</p>
<p>There are many robust methods out there. To recap, some include:</p>
<ul>
<li><p>Bootstrapping - useful in small samples when normal errors cannot be assumed</p></li>
<li><p>Heteroscedasticity-consistent standard errors - useful when homoscedasticity cannot be assumed</p></li>
<li><p><em>M-</em>type estimators - useful when we have influential cases or asymmetric error distributions, but can also deal with heteroscedasticity.</p></li>
</ul>
<p>Given that we’re dealing with asymmetric errors, heteroscedasticity, <em>and</em> potential influential cases (<a href="#fig-gzlms-assumptions" class="quarto-xref">Figure&nbsp;<span>4</span></a>), let’s fit an <em>MM</em>-estimator:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>belay_rob <span class="ot">&lt;-</span> robustbase<span class="sc">::</span><span class="fu">lmrob</span>(reaction_time <span class="sc">~</span> assisted_break <span class="sc">+</span> climbing_exp <span class="sc">+</span> distracted <span class="sc">+</span> fall_m, <span class="at">data =</span> belay_tib)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can now request the parameter estimates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>belay_rob <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">parameters</span>() <span class="sc">|&gt;</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-gzlms-params" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-gzlms-params-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3
</figcaption>
<div aria-describedby="tbl-gzlms-params-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment caption-top table table-sm table-striped small">
<caption>Fixed Effects</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 26%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Coefficient</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">t(147)</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">689.26</td>
<td style="text-align: center;">53.94</td>
<td style="text-align: center;">(582.66, 795.86)</td>
<td style="text-align: center;">12.78</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">assisted break</td>
<td style="text-align: center;">-26.77</td>
<td style="text-align: center;">14.04</td>
<td style="text-align: center;">(-54.52, 0.98)</td>
<td style="text-align: center;">-1.91</td>
<td style="text-align: center;">0.059</td>
</tr>
<tr class="odd">
<td style="text-align: left;">climbing exp</td>
<td style="text-align: center;">-53.49</td>
<td style="text-align: center;">6.23</td>
<td style="text-align: center;">(-65.79, -41.18)</td>
<td style="text-align: center;">-8.59</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">distracted</td>
<td style="text-align: center;">50.84</td>
<td style="text-align: center;">15.48</td>
<td style="text-align: center;">(20.26, 81.42)</td>
<td style="text-align: center;">3.29</td>
<td style="text-align: center;">0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fall m</td>
<td style="text-align: center;">76.16</td>
<td style="text-align: center;">20.66</td>
<td style="text-align: center;">(35.33, 116.99)</td>
<td style="text-align: center;">3.69</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><br></p>
<p>There is a negative but non-significant difference in reaction time between belayers who used an assisted breaking device compared to those who didn’t, <em>b</em> = -26.77, 95% CI [-54.52, 0.98], <em>SE</em> = 14.04, <em>t</em> = -1.91, <em>p</em> = 0.059 - those using a breaking device were only -26.77 quicker. Based on this we cannot reject the null hypothesis of no difference between belaying devices.</p>
<p>Belayers with more climbing experience were faster to stop a fall, while holding other predictors constant, <em>b</em> = -53.49, 95% CI [-65.79, -41.18], <em>SE</em> = 6.23, <em>t</em> = -8.59, <em>p</em> &lt; .001. With a one year increase in climbing experience, we can expect the reaction time to reduce by -53.49 . The 95% confidence interval suggest this reduction could be as large as -41.18 or as low as -65.79 , assuming this confidence interval is one the 95% that contain the true population value. If the null hypothesis were true, the probability of finding an effect this large is sufficiently unlikely, <em>p</em> &lt; .001. We therefore reject the hypothesis of null effect and retain H<sub>2</sub>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What’s with this awful language…
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Look, if it helps you make sense of this, here’s a slightly more direct version:</p>
<blockquote class="blockquote">
<p>It is unlikely that we would find this difference if the effect itself was in reality 0, <em>p</em> &lt; .001, which is in support of H<sub>2</sub>.</p>
</blockquote>
<p>However, it is <em>technically and statistically incorrect</em> . A statistically significant <em>p</em>-value can never provide support for an alternative hypothesis, no matter how small. It only tells us if the alternative hypothesis is sufficiently unlikely <em>if</em> the null is true, but it doesn’t tell the probability of the null or the alternative hypothesis being true. Bayes Factors <em>can</em> tell us that, but that’s a whole other module.</p>
</div>
</div>
</div>
<p>The effects of both covariates were also statistically significant. Distracted belayers were slower to react <em>b</em> = 50.84, 95% CI [20.26, 81.42], <em>SE</em> = 15.48, <em>t</em> = 3.29, <em>p</em> = 0.001 , while an increase in 1 metre of fall length was associated with an increase of 76.16 milliseconds in time taken to stop the fall (<em>p</em> &lt; .001). This is not surprising, is the climber had a greater distance to fall before the rope ran out of slack.</p>
</section>
<section id="making-predictions" class="level2">
<h2 class="anchored" data-anchor-id="making-predictions">Making predictions</h2>
<p>Now that we’ve caught up, let’s push our models even further. Generally, there are two reasons why we might want to build a statistical model. (1) To test a theory and help build a theoretical framework by explaining the roles of key variables or (2) to make a prediction. These two are not mutually exclusive.</p>
<p>Recall that a linear model can be describe as:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1X_{1i} + \beta_2X_{2i} + ... + \beta_nX_{ni} + \varepsilon_i
\]</span></p>
<p>That is, the outcome <span class="math inline">\(Y\)</span> for the participant <span class="math inline">\(i\)</span> is predicted from the sum of the intercept <span class="math inline">\(\beta_0\)</span> a value of each predictor for that participant (<span class="math inline">\(X_1, X_2...\)</span>), multiplied by the parameter estimate for each predictor, respectively (<span class="math inline">\(\beta_1 , \beta_2 ...\)</span>). Each participant will also have their own error in prediction <span class="math inline">\(\varepsilon_i\)</span> .</p>
<section id="predictions-within-the-observed-data" class="level3">
<h3 class="anchored" data-anchor-id="predictions-within-the-observed-data">Predictions within the observed data</h3>
<p>The equation specific to our model is:</p>
<p><span class="math display">\[
\begin{split}
\mbox{reaction time}_i = \beta_0 &amp;+ \beta_1\mbox{assisted break}_{i} \\
&amp;+ \beta_2\mbox{climbing experience}_{i} \\
&amp;+ \beta_3\mbox{distracted}_{i} \\
&amp;+ \beta_4\mbox{fall distance}_{i} \\
&amp; + \varepsilon_i
\end{split}
\]</span></p>
<p>We’ve worked out the beta values, so let’s plug them in from <a href="#tbl-gzlms-params" class="quarto-xref">Table&nbsp;<span>3</span></a> :</p>
<p><span class="math display">\[
\begin{split}
\mbox{reaction time}_i = 689 &amp;-26.77*\mbox{assisted break}_{i} \\
&amp;- 53.49*\mbox{climbing experience}_{i} \\
&amp;+ 50.84*\mbox{distracted}_{i} \\
&amp;+ 76.16*\mbox{fall distance}_{i} \\
&amp;+ \varepsilon_i
\end{split}
\]</span></p>
<p>Let’s test this - how about we use the predictor values from the first participant from our dataset in <a href="#tbl-gzlms-tib" class="quarto-xref">Table&nbsp;<span>1</span></a> to see if we can use our model to predict their outcome?</p>
<p>Here are their values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>belay_tib[<span class="dv">1</span>, ] <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 20%">
<col style="width: 22%">
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">subj_id</th>
<th style="text-align: right;">reaction_time</th>
<th style="text-align: right;">assisted_break</th>
<th style="text-align: right;">distracted</th>
<th style="text-align: right;">climbing_exp</th>
<th style="text-align: right;">fall_m</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1017</td>
<td style="text-align: right;">847.40</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.10</td>
<td style="text-align: right;">2.10</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<p>We can assign these values into objects and then rewrite the equation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>assisted_break_i <span class="ot">&lt;-</span> <span class="dv">0</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>climbing_exp_i <span class="ot">&lt;-</span> <span class="fl">3.1</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>distracted_i <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>fall_m_i <span class="ot">&lt;-</span> <span class="fl">2.1</span> </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fl">689.29</span> <span class="sc">-</span> <span class="fl">26.77</span> <span class="sc">*</span> assisted_break_i <span class="sc">-</span> <span class="fl">53.49</span> <span class="sc">*</span> climbing_exp_i <span class="sc">+</span> <span class="fl">50.84</span> <span class="sc">*</span> distracted_i <span class="sc">+</span> <span class="fl">76.16</span> <span class="sc">*</span> fall_m_i</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 734.247</code></pre>
</div>
</div>
<p>If we run the code chunk above, the model predicts that the first participant should have a reaction time of milliseconds. However, their <em>actual</em> reaction was 847.4. This is because we forgot the last part of the equation, <span class="math inline">\(\varepsilon_i\)</span>. This represents the <em>residual</em> for our participant. We <em>can</em> extract it from the model and add it to the equation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>residual_i <span class="ot">&lt;-</span> belay_rob<span class="sc">$</span>residuals[<span class="dv">1</span>] <span class="co"># extract the residual for the first participant</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fl">689.29</span> <span class="sc">-</span> <span class="fl">26.77</span> <span class="sc">*</span> assisted_break_i <span class="sc">-</span> <span class="fl">53.49</span> <span class="sc">*</span> climbing_exp_i <span class="sc">+</span> <span class="fl">50.84</span> <span class="sc">*</span> distracted_i <span class="sc">+</span> <span class="fl">76.16</span> <span class="sc">*</span> fall_m_i <span class="sc">+</span> residual_i</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
847.4194 </code></pre>
</div>
</div>
<p>In this case, the value matches perfectly, but this only works if we are predicting values that are already in the model, because we can extract the residual direct. In practice, we often want to predict values for individuals who are <em>not</em> in the dataset - in such a case we accept we’ll often be slightly off because we don’t know how large the residual could be, but our prediction is our best guess that will result in the least possible error.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Is there an easier way…?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Yes. R automatically computes the values your model predicts for every single participant. We did this manually above using the equation, but we could have just as easily done it with code. Fitted values can be accessed as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>belay_rob<span class="sc">$</span>fitted.values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is a list of values that corresponds to the rows in our dataset. So the first value corresponds to the predicted value of reaction for the first participant:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>belay_rob<span class="sc">$</span>fitted.values[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
734.2276 </code></pre>
</div>
</div>
<p>This is exactly the value we calculated manually, so it’s good to know our maths works!</p>
</div>
</div>
</div>
</section>
<section id="sec-going-beyond-the-data" class="level3">
<h3 class="anchored" data-anchor-id="sec-going-beyond-the-data">Going beyond the data</h3>
<p>The nice thing about modelling relationships as straight lines is that once we know the intercept and the slope, we can pretty much extend the line in either direction and make predictions for values that are not represented in your dataset. Consider <a href="#fig-gzlms-h1" class="quarto-xref">Figure&nbsp;<span>1</span></a> . Although the line only spans the range of the data, we could extend each end to make predictions.</p>
<p>Say that we’re interested in what the model predicts for individuals with no climbing experience, or, on the other hand, with extensive climbing experience. We’re going to create a new tibble with the values of <code>climbing_exp</code> for which we want to predict, that is, for belayers with anywhere between 0 and 20 years of experience.</p>
<p>Then we’ll hold the other predictors constant. For factors, we’ll hold the values at the baseline, so 0 or “No” for both <code>assisted_break</code> and <code>distracted</code> . The continuous predictor - fall length - will be held constant at the average value of <code>fall_m</code> from <a href="#tbl-gzlms-describe" class="quarto-xref">Table&nbsp;<span>2</span></a> . We’ll use the <code>tibble</code> function and store the result into an object called <code>prediction_tib</code> .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>prediction_tib <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">climbing_exp =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">assisted_break =</span> <span class="dv">0</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">distracted =</span> <span class="dv">0</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">fall_m =</span> <span class="fl">1.82</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Inspect the tibble:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>prediction_tib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-74472330289cd43f8034" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-74472330289cd43f8034">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21"],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>climbing_exp<\/th>\n      <th>assisted_break<\/th>\n      <th>distracted<\/th>\n      <th>fall_m<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"climbing_exp","targets":1},{"name":"assisted_break","targets":2},{"name":"distracted","targets":3},{"name":"fall_m","targets":4}],"order":[],"autoWidth":false,"orderClasses":false},"selection":{"mode":"multiple","selected":null,"target":"row","selectable":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<p>As requested, values in all rows are identical except for <code>climbing_exp</code>, which is changing. Now we can use this table to make predictions. The <code>predict</code> function is very handy here: it only takes two arguments: the model and the tibble with values which we want to use for prediction.</p>
<p>On its own, it can be used like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(belay_rob, prediction_tib)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Which returns a vector of predicted values. Let’s be a little more efficient - we’re going to take the tibble we’ve just created - <code>prediction_tib</code> and use the <code>mutate</code> function to create a new column called <code>predicted_rt</code> . This column is created by applying the <code>predict</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-19"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><a class="code-annotation-anchor" data-target-cell="annotated-cell-19" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-19-1" class="code-annotation-target"><a href="#annotated-cell-19-1" aria-hidden="true" tabindex="-1"></a>prediction_tib <span class="ot">&lt;-</span> prediction_tib <span class="sc">|&gt;</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-19" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-19-2" class="code-annotation-target"><a href="#annotated-cell-19-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-19" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-19-3" class="code-annotation-target"><a href="#annotated-cell-19-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">predicted_rt =</span> <span class="fu">predict</span>(belay_rob, prediction_tib)</span>
<span id="annotated-cell-19-4"><a href="#annotated-cell-19-4" aria-hidden="true" tabindex="-1"></a>  )</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-19" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-19" data-code-lines="1" data-code-annotation="1">Take the existing <code>prediction_tib</code>. We’re updating an existing object instead of creating a new one, so the assignment operator <code>&lt;-</code> is also pointing towards <code>prediction_tib</code>.</span>
</dd>
<dt data-target-cell="annotated-cell-19" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-19" data-code-lines="2" data-code-annotation="2">Use the <code>mutate</code> function to create a new variable.</span>
</dd>
<dt data-target-cell="annotated-cell-19" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-19" data-code-lines="3" data-code-annotation="3">Call this new variable <code>predicted_rt</code>. Create <code>predicted_rt</code> by applying the <code>predict</code> function to the robust model <code>belay_rob</code> and the <code>prediction_tib</code> which contains all the values for which we’re trying to generate predictions.</span>
</dd>
</dl>
</div>
</div>
<p><br></p>
<p>Once again, let’s inspect our work:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>prediction_tib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-d369ede9b8577434d565" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-d369ede9b8577434d565">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21"],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82,1.82],[827.869912324782,774.3831852076386,720.8964580904951,667.4097309733517,613.9230038562082,560.4362767390647,506.9495496219213,453.4628225047779,399.9760953876344,346.489368270491,293.0026411533475,239.515914036204,186.0291869190606,132.5424598019171,79.05573268477366,25.5690055676302,-27.91772154951326,-81.40444866665672,-134.8911757838002,-188.3779029009436,-241.8646300180871]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>climbing_exp<\/th>\n      <th>assisted_break<\/th>\n      <th>distracted<\/th>\n      <th>fall_m<\/th>\n      <th>predicted_rt<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"climbing_exp","targets":1},{"name":"assisted_break","targets":2},{"name":"distracted","targets":3},{"name":"fall_m","targets":4},{"name":"predicted_rt","targets":5}],"order":[],"autoWidth":false,"orderClasses":false},"selection":{"mode":"multiple","selected":null,"target":"row","selectable":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<p>This time the tibble has an extra column with predicted values. If you inspected the <code>predicted_rt</code> values, you may already noticed that something is wrong. Let’s add these on a plot so we can see the prediction more clearly:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>belay_tib <span class="sc">|&gt;</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span> _, <span class="fu">aes</span>(<span class="at">x =</span> climbing_exp, <span class="at">y =</span> reaction_time)) <span class="sc">+</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">colour =</span> <span class="st">"yellowgreen"</span>) <span class="sc">+</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">colour =</span> <span class="st">"darkred"</span>, <span class="at">data =</span> prediction_tib, <span class="fu">aes</span>(<span class="at">x =</span> climbing_exp, <span class="at">y =</span> predicted_rt)) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Belayer's climbing experience (in years)"</span>, <span class="at">y =</span> <span class="st">"Reaction time (ms) to break the fall"</span>) <span class="sc">+</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-glzms-rob-pred" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-glzms-rob-pred-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01_gzlms_files/figure-html/fig-glzms-rob-pred-1.png" id="fig-glzms-rob-pred" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-glzms-rob-pred-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5
</figcaption>
</figure>
</div>
</div>
</div>
<p>We start the scatterplot above as usual. Then we add <code>stat_smooth</code> but instruct ggplot to use a <em>different</em> dataset and different aesthetics than the one we provided when we initialised the plot, so we can show our prediction that goes beyond the data.</p>
<p>If we look at what the model predicts for belayers with no climbing experience, it’s not particularly unusual. The reaction time is longer, though notice there are four individuals in the top left above the line who have more experience but also seem to have longer reaction times than newbies. The model doesn’t do a very good job predicting values for these belayers.</p>
<p>Now let’s look at very experienced belayers. The reaction continues going down, however as we get to about 15 years of experience, the model starts predicting <em>negative</em> reaction times.</p>
<p>This, of course, makes no sense. It turns out this the convenient feature of being able to easily extend the line once we know it’s starting point and the direction is also the downfall of linear models - the line can go on forever and <em>will</em> inevitably predict nonsense if the linear model is not the appropriate model.</p>
<p>Robust models are also - if not more - susceptible. They down-weigh scores with high residuals, especially scores at the tails of asymmetric distributions. The robust parameter estimate is therefore very good at describing what is happening at the centre of the distribution and make predictions for these scores, but it cannot describe or make predictions for individuals at the tails. That doesn’t mean robust models are useless. We just need be clear about what our intentions are and what we’re hoping to get out of the model. If the goal is to summarise the “typical individual” and we don’t particularly care about what’s happening at the tails, robust models might be just the solution we need.</p>
<p>If, however, we hope to be able to make conclusions about the whole distribution, we must take a different approach.</p>
</section>
</section>
<section id="introduction-to-gzlm" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-gzlm">Introduction to GzLM</h2>
<p>GzLM are useful and versatile, but we shouldn’t just think about them as a “fix” for GLM models that don’t meet the assumptions. When it comes to data analysis that involves confirmatory hypothesis testing with <em>p</em>-values, it’s generally a bad idea to base key analytic decisions on something we’ve discovered in the data because doing so invalidates the <em>p</em>-values derived from our models. In other words, a good analytic pipeline should <em>not</em> take the form of (1) fit an OLS model (2) discover violated assumptions (3) fit GzLM to fix the problems.</p>
<p>Instead, we should think about the data generating process when we are planning the analyses, or, better yet, before we even start data collection. Considering the variables we’re aiming to collect, what might the distributions look like? Is normal distribution a reasonable expectation? Is variance that doesn’t change at different values of the predictors a reasonable expectation? More often than not, the answer to the latter two questions is no.</p>
<section id="how-is-gzlm-different-to-glm" class="level3">
<h3 class="anchored" data-anchor-id="how-is-gzlm-different-to-glm">How is GzLM different to GLM?</h3>
<p>GLM uses Ordinary Least Squares (OLS) estimation to fit models. The goal of OLS is to find the values of <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_2\)</span> … so that the sum of squared errors (SSE) is as small is it can be given the data provided. Consider <a href="#fig-gzlms-h1" class="quarto-xref">Figure&nbsp;<span>1</span></a> : if we were to measure the distance of each point from the line (i.e.&nbsp;the residual), square each distance and then sum all of them together, we’d get an SSE. For the model depicted in <a href="#fig-gzlms-h1" class="quarto-xref">Figure&nbsp;<span>1</span></a>, the line is the most optimal line that gives the smallest possible SSE.</p>
<p>The process is a little different for robust models using <em>M</em>-type estimation wherein the cases with the largest residuals get itteratively down-weighted until an optimal line is found, but the starting point is the result of OLS estimation.</p>
<section id="maximum-likelihood-estimation" class="level4">
<h4 class="anchored" data-anchor-id="maximum-likelihood-estimation">Maximum Likelihood estimation</h4>
<p>GzLM use <em>Maximum Likelihood Estimation</em> (ML)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. ML aims to find an optimal way to fit a given distribution to the data. It searches for the values of the the parameter estimates where a given <em>assumed distribution</em> is the most likely. In other words, where the <em>likelihood</em> of that distribution is at its <em>maximum</em>.</p>
</section>
<section id="sec-conditional-distributions" class="level4">
<h4 class="anchored" data-anchor-id="sec-conditional-distributions">Conditional distributions</h4>
<p>What are we assuming the distribution <em>of</em>?</p>
<p>We know that OLS makes assumptions about the shape of errors in the population model - that is, it assumes they are normally distributed. Various guides will sometimes claim that we need to be checking a so called “response distribution”, which is just another word for the outcome. This is not quite right.</p>
<p>ML estimation makes assumptions about the <em>conditional distribution</em> of the outcome. Say that we’re trying to model the relationship between X and Y where</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 X_i
\]</span></p>
<p>If we model this as a Gaussian model - that is, a model assuming a normal conditional distribution - we’re assuming that that the outcome Y is normally distribution <em>at any value of X</em>. As a formula, we would write:</p>
<p><span class="math display">\[
P(Y|X) \sim N(\mu, \sigma^2)
\]</span></p>
<p>That is, any Y value <em>given</em> any X values comes from a normal distribution with a mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span> .</p>
<p>The nice thing about GzLMs is that we can just relax this assumption if a different distribution is more appropriate.</p>
<p>For example here:</p>
<p><span class="math display">\[
P(Y|X) \sim \Gamma(\alpha, \theta)
\]</span></p>
<p>we’re saying that the conditional distribution of Y given X is a Gamma distribution with a shape <span class="math inline">\(\alpha\)</span> and scale <span class="math inline">\(\theta\)</span> . More on this in section <a href="01a_gzlms_skewed/">Modelling Skewness</a>.</p>
<p>This distinction between the distribution of the outcome variable and the <em>conditional</em> distribution of the outcome variable is important. Similar to OLS, if we check the distribution of the outcome, it often will resemble the conditional distribution but this not a given - the outcome distribution will be composed of the many conditional distributions at various levels of the predictor(s) and there is no guarantee that the shape of all of these distributions will resemble the one we’re modelling when combined into the outcome variable.</p>
<p>Have a look at <a href="#fig-nonnorm-outcome" class="quarto-xref">Figure&nbsp;<span>6</span></a> . Hopefully you’ll agree that this is <em>not</em> a normal distribution:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-nonnorm-outcome" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nonnorm-outcome-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01_gzlms_files/figure-html/fig-nonnorm-outcome-1.png" id="fig-nonnorm-outcome" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-nonnorm-outcome-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6
</figcaption>
</figure>
</div>
</div>
</div>
<p>However, if we were do decompose it, we’d find that the distribution in <a href="#fig-nonnorm-outcome" class="quarto-xref">Figure&nbsp;<span>6</span></a> is actually built out of <em>many</em> normal distributions with different means:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-nonnorm-conditional" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nonnorm-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01_gzlms_files/figure-html/fig-nonnorm-conditional-1.png" id="fig-nonnorm-conditional" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-nonnorm-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7
</figcaption>
</figure>
</div>
</div>
</div>
<p>Therefore checking the distribution of the outcome itself might be a good starting point, but it can lead us astray, especially if the conditional distribution substantially varies in parameters.</p>
</section>
<section id="sec-mean-variance-relationship" class="level4">
<h4 class="anchored" data-anchor-id="sec-mean-variance-relationship">Mean-variance relationship</h4>
<p>In GLM, we assume a constant variance of errors. That is, regardless of the predicted value, the spread of errors remains the same - this is homoscedasticity. Its violation, as we saw in <a href="#fig-gzlms-assumptions" class="quarto-xref">Figure&nbsp;<span>4</span></a> is called heteroscedasticity.</p>
<p><em>M</em>-type robust estimators attempt to fix the impact of heteroscedasticity by (1) down-weighting cases with extreme residuals and (2) using an alternative estimator for the standard errors. Either way, heteroscedasticity is seen as some nuisance to be fixed.</p>
<p>On the other hand, GzLM can model various forms of heteroscedasticty explicitly and build these changes in variance into predictions. Different conditional distributions make different assumptions about the mean-variance relationship. For example, Gamma models assume a quadratic relationship:</p>
<p><span class="math display">\[
V(Y) = E(Y)^2
\]</span></p>
<p>i.e.&nbsp;in a given conditional distribution, the variance of scores will be equal to the squared expected<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> value. Alternatively, the Poisson distribution can model a situation where the expected value is equal to the variance.</p>
<p><span class="math display">\[
V(Y) = E(Y)
\]</span></p>
<p>We’ll cover these situations in more detail in the upcoming weeks. The bottom line is that GzLM offers a lot more flexibility than GLM, which can be useful in a variety of applied scenarios. So before we get too bogged down in terminology, let’s fit one more <em>bad</em> model to get the hang of the coding, and then we’ll finally move on to modelling tackling out hypotheses properly by choosing a more appropriate modelling approach.</p>
</section>
</section>
<section id="sec-fitting-gzlm-in-r" class="level3">
<h3 class="anchored" data-anchor-id="sec-fitting-gzlm-in-r">Fitting GzLM in R</h3>
<p>So let’s fit our model. We’re still going to (wrongly) assume the normal conditional distribution for our outcome, but this time we’ll fit the model using maximum likelihood estimation instead of OLS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-22"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-22-1" class="code-annotation-target"><a href="#annotated-cell-22-1" aria-hidden="true" tabindex="-1"></a>belay_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-22-2" class="code-annotation-target"><a href="#annotated-cell-22-2" aria-hidden="true" tabindex="-1"></a>  reaction_time <span class="sc">~</span> assisted_break <span class="sc">+</span> climbing_exp <span class="sc">+</span> distracted <span class="sc">+</span> fall_m,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-22-3" class="code-annotation-target"><a href="#annotated-cell-22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">gaussian</span>(<span class="at">link =</span> <span class="st">"identity"</span>),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-22-4" class="code-annotation-target"><a href="#annotated-cell-22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> belay_tib</span>
<span id="annotated-cell-22-5"><a href="#annotated-cell-22-5" aria-hidden="true" tabindex="-1"></a>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-22" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-22" data-code-lines="1" data-code-annotation="1">Use the <code>glm()</code> function instead of <code>lm()</code> . Store into an object <code>belay_glm</code></span>
</dd>
<dt data-target-cell="annotated-cell-22" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-22" data-code-lines="2" data-code-annotation="2">Specify the formula - same as before.</span>
</dd>
<dt data-target-cell="annotated-cell-22" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-22" data-code-lines="3" data-code-annotation="3">Specify the family and the link function (see below)</span>
</dd>
<dt data-target-cell="annotated-cell-22" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-22" data-code-lines="4" data-code-annotation="4">Specify the dataset - same as before</span>
</dd>
</dl>
</div>
</div>
<p>The main difference from the OLS model or the robust model is this line: <code>family = gaussian(link = "identity")</code> . Here, we’re telling R to assume normal conditional distribution (i.e.&nbsp;gaussian). We’re also asking R <em>not</em> to transform the variables in any way and model the relationship as linear directly (`<code>link = "identity"</code>). We’ll talk about what exactly this means in the upcoming sections but for now you just need to understand that the <code>link = "identity"</code> ensures that the parameter estimates we get out of the model can be interpreted as we’re used to, as a linear increase in the outcome expected with an increase of one unit in the predictor.</p>
<p>We can run the model checks as normal - the output is the same as before and can be interpreted as such, so there’s no need to repeat it here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-23"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-23-1"><a href="#annotated-cell-23-1" aria-hidden="true" tabindex="-1"></a>belay_glm <span class="sc">|&gt;</span> </span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-23" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-23-2" class="code-annotation-target"><a href="#annotated-cell-23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">check_model</span>()</span>
<span id="annotated-cell-23-3"><a href="#annotated-cell-23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-23-4"><a href="#annotated-cell-23-4" aria-hidden="true" tabindex="-1"></a>belay_glm <span class="sc">|&gt;</span> </span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-23" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-23-5" class="code-annotation-target"><a href="#annotated-cell-23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">performance</span>()</span>
<span id="annotated-cell-23-6"><a href="#annotated-cell-23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-23-7"><a href="#annotated-cell-23-7" aria-hidden="true" tabindex="-1"></a>belay_glm <span class="sc">|&gt;</span> </span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-23" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-23-8" class="code-annotation-target"><a href="#annotated-cell-23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">test_wald</span>()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-23" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-23" data-code-lines="2" data-code-annotation="1">Check model assumptions</span>
</dd>
<dt data-target-cell="annotated-cell-23" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-23" data-code-lines="5" data-code-annotation="2">Overall fit statistics</span>
</dd>
<dt data-target-cell="annotated-cell-23" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-23" data-code-lines="8" data-code-annotation="3">Test of model fit</span>
</dd>
</dl>
</div>
</div>
<p>The parameter estimates will also be identical. The ML estimation is an algorithmic process with several steps, in which the model tries out different values before converging on ones with the maximum likelihood given the data. However, with Gaussian models, this algorithm converges on the exact same parameter estimates as OLS right after the first step.</p>
<p>We’ve not actually produced the OLS estimates before, so let’s compare them to the ML estimates side by side:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">OLS (GLM) estimates</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">ML (GzLM) estimates</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>belay_lm <span class="sc">|&gt;</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">parameters</span>() <span class="sc">|&gt;</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 26%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Coefficient</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">t(147)</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">732.93</td>
<td style="text-align: center;">51.00</td>
<td style="text-align: center;">(632.14, 833.73)</td>
<td style="text-align: center;">14.37</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">assisted break</td>
<td style="text-align: center;">-33.03</td>
<td style="text-align: center;">17.07</td>
<td style="text-align: center;">(-66.77, 0.71)</td>
<td style="text-align: center;">-1.93</td>
<td style="text-align: center;">0.055</td>
</tr>
<tr class="odd">
<td style="text-align: left;">climbing exp</td>
<td style="text-align: center;">-59.96</td>
<td style="text-align: center;">5.80</td>
<td style="text-align: center;">(-71.42, -48.49)</td>
<td style="text-align: center;">-10.33</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">distracted</td>
<td style="text-align: center;">70.29</td>
<td style="text-align: center;">16.90</td>
<td style="text-align: center;">(36.89, 103.69)</td>
<td style="text-align: center;">4.16</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fall m</td>
<td style="text-align: center;">77.54</td>
<td style="text-align: center;">20.86</td>
<td style="text-align: center;">(36.32, 118.77)</td>
<td style="text-align: center;">3.72</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>belay_glm <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">parameters</span>() <span class="sc">|&gt;</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 26%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Coefficient</th>
<th style="text-align: center;">SE</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">t(147)</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">732.93</td>
<td style="text-align: center;">51.00</td>
<td style="text-align: center;">(632.97, 832.90)</td>
<td style="text-align: center;">14.37</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">assisted break</td>
<td style="text-align: center;">-33.03</td>
<td style="text-align: center;">17.07</td>
<td style="text-align: center;">(-66.49, 0.43)</td>
<td style="text-align: center;">-1.93</td>
<td style="text-align: center;">0.053</td>
</tr>
<tr class="odd">
<td style="text-align: left;">climbing exp</td>
<td style="text-align: center;">-59.96</td>
<td style="text-align: center;">5.80</td>
<td style="text-align: center;">(-71.33, -48.58)</td>
<td style="text-align: center;">-10.33</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">distracted</td>
<td style="text-align: center;">70.29</td>
<td style="text-align: center;">16.90</td>
<td style="text-align: center;">(37.17, 103.42)</td>
<td style="text-align: center;">4.16</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fall m</td>
<td style="text-align: center;">77.54</td>
<td style="text-align: center;">20.86</td>
<td style="text-align: center;">(36.65, 118.43)</td>
<td style="text-align: center;">3.72</td>
<td style="text-align: center;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<p>Although the estimates themselves are the same, the confidence intervals and the <em>p</em>-values are not. This is deliberate. When we fit OLS models, we use the critical <em>t</em> statistic<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> based on the residual degrees of freedom to construct the CIs. The test statistic is then calculated by dividing the parameter estimate by its standard error, and this is compared against a theoretical <em>t</em> distribution to calculate the <em>p</em>-value.</p>
<p>When we fitted the GzLM, we explicitly told R to assume a normal/Gaussian distribution. So the model takes us for our word, and instead of using the <em>t</em> distribution, it compares the test statistic against a normal distribution. Likewise, the CIs are constructed using the critical <em>Z</em> value, not the critical <em>t</em> value. The <code>parameters</code> function is quite clever in that it automatically detects what kind of model we fitted and gives us the result based on that.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Of course, if we were to actually run any of the model checks, we’d still find that the model is fundamentally flawed. Regardless of the approach, a normal distribution is not the appropriate distribution to be assuming here. If we fit a robust model, the predictions we’re generating are only useful for the middle of the distribution, while the predictions at the tails breach the realm of science-fiction with reality-bending reaction times. If we want to create a useful model of the reality, we need to change the assumptions we’re making about the data-generating process.</p>
<section id="welcome-to-the-family" class="level3">
<h3 class="anchored" data-anchor-id="welcome-to-the-family">Welcome to the family</h3>
<p>The General Linear Model encompasses many types of models that use OLS estimation (like the t-test, ANOVA, regression and others). The <em>Generalised</em> Linear Model takes this even further and can model various forms of the <strong>Exponential Family</strong> . This may seem counter-intuitive because when we say “Exponential” we often imagine a line that grows or descends steeply (or “exponentially”), but this distribution family in an overarching group of distributions that come in many shapes and sizes, including:</p>
<ul>
<li><p>Bernoulli distribution (often assumed in logistic regression)</p></li>
<li><p>Chi-squared distribution</p></li>
<li><p>Dirichlet distribution</p></li>
<li><p>Exponential distribution</p></li>
<li><p>Gamma distribution</p></li>
<li><p>Normal distribution (yes, even normal distribution)</p></li>
<li><p>Poisson distribution</p></li>
</ul>
<p>and others. We’re going to learn about some of these in the coming weeks.</p>
</section>
</section>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<section id="what-does-this-code-do" class="level3">
<h3 class="anchored" data-anchor-id="what-does-this-code-do">What does this code do?</h3>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Here’s all the code we have written in this section. Can you remember what each line of each codechunk does? Are there any codechunks that you struggle to make sense of? Make sure to revisit the section in which it is used and take notes.</p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(easystats) </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>belay_tib <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/climbing_data.csv"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  readr<span class="sc">::</span><span class="fu">read_csv</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-tbl-cap="">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>belay_tib <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">describe_distribution</span>(<span class="at">select =</span> <span class="sc">-</span>subj_id) <span class="sc">|&gt;</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>belay_tib <span class="sc">|&gt;</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span> _, <span class="fu">aes</span>(<span class="at">x =</span> climbing_exp, <span class="at">y =</span> reaction_time)) <span class="sc">+</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">colour =</span> <span class="st">"yellowgreen"</span>) <span class="sc">+</span> </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">colour =</span> <span class="st">"steelblue"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1030.5</span>)) <span class="sc">+</span> </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Belayer's climbing experience (in years)"</span>, <span class="at">y =</span> <span class="st">"Reaction time (ms) to break the fall"</span>) <span class="sc">+</span> </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>belay_tib <span class="sc">|&gt;</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span> _, <span class="fu">aes</span>(<span class="at">x =</span> reaction_time)) <span class="sc">+</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">colour =</span> <span class="st">"steelblue"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Reaction time (ms) to break the fall"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span> </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>belay_lm <span class="sc">|&gt;</span> <span class="fu">check_model</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>belay_lm <span class="sc">|&gt;</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">performance</span>() <span class="sc">|&gt;</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>belay_lm <span class="sc">|&gt;</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">test_wald</span>() <span class="sc">|&gt;</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-tbl-cap="">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>belay_rob <span class="sc">|&gt;</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">parameters</span>() <span class="sc">|&gt;</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>prediction_tib <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">climbing_exp =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">assisted_break =</span> <span class="dv">0</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">distracted =</span> <span class="dv">0</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">fall_m =</span> <span class="fl">1.82</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(belay_rob, prediction_tib)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>belay_glm <span class="sc">|&gt;</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">check_model</span>()  </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>belay_glm <span class="sc">|&gt;</span> </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">performance</span>()  </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>belay_glm <span class="sc">|&gt;</span> </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">test_wald</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>belay_glm <span class="sc">|&gt;</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">parameters</span>() <span class="sc">|&gt;</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">display</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="annotated-cell-27"><pre class="sourceCode r code-annotation-code code-with-copy"><code class="sourceCode r"><span id="annotated-cell-27-1"><a href="#annotated-cell-27-1" aria-hidden="true" tabindex="-1"></a>belay_tib <span class="sc">|&gt;</span> </span>
<span id="annotated-cell-27-2"><a href="#annotated-cell-27-2" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(<span class="at">data =</span> _, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(assisted_break), <span class="at">y =</span> reaction_time)) <span class="sc">+</span></span>
<span id="annotated-cell-27-3"><a href="#annotated-cell-27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">colour =</span> <span class="st">"yellowgreen"</span>, <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>)) <span class="sc">+</span> </span>
<span id="annotated-cell-27-4"><a href="#annotated-cell-27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_cl_normal"</span>) <span class="sc">+</span> </span>
<span id="annotated-cell-27-5"><a href="#annotated-cell-27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1030.5</span>)) <span class="sc">+</span> </span>
<span id="annotated-cell-27-6"><a href="#annotated-cell-27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Did the belayer used an assisted breaking device"</span>, <span class="at">y =</span> <span class="st">"Reaction time (ms) to break the fall"</span>) <span class="sc">+</span> </span>
<span id="annotated-cell-27-7"><a href="#annotated-cell-27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>A “belayer” is the person on the ground, managing the rope and ensuring the climber on the wall is safe.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Unhelpfully, the ML abbreviation is also reserved for “Machine Learning”, so just be aware of this if you’re using any external resources.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>You could substitute the term “expected” with “predicted”. The only difference is that we tend to use “predicted” when talking about a single value, and “expected” when talking about a whole distribution, but for all intents and purposes, they are the same.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>This is not the same as the t statistic that we see in the tables.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Welcome to Advanced Statistics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Welcome to Advanced Statistics</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./01a_gzlms_skewed.html" class="pagination-link" aria-label="Modelling skewness">
        <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Modelling skewness</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>